project:
  type: website
  output-dir: docs
website:
  title: "GAMLSS Lavras Short Course 2025"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - Why_GAMLSS.qmd
      - TheRsoftware.qmd
      - Distributions.qmd
      - fitting.qmd
      - interpret.qmd

      
sidebar:
  contents: auto
      
format:
  html:
    theme: sky
    css: styles.css
    toc: true

editor: visual

